"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.9.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from django.contrib.messages import constants as message_constants

MESSAGE_TAGS = {message_constants.ERROR: 'danger'}

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!(%e(7zo4+kan(h!eb%yt3&r_2#p&jf=43&$m1xfqrd0n591(v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
PAGINATION_LENGTH = 25
ALLOWED_HOSTS = ["*"]

# SSL
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_FRAME_DENY = True #Prevents clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True # Stop browser predicting asset content types
SECURE_BROWSER_XSS_FILTER = True # XXS Protection

SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'voting_system',
    'djangosecure',
    'sslserver',
    
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'admin',
        'USER': 'admin',
        'PASSWORD': 'admin',
        'HOST': '5.179.102.239',
        'PORT': '20001',
    },
    'voter_auth': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'voterauth',
        'USER': 'voterauth',
        'PASSWORD': 'voterauth',
        'HOST': '5.179.102.239',
        'PORT': '20002',
    },
    'region1': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'region1',
        'USER': 'region1',
        'PASSWORD': 'region1',
        'HOST': '5.179.102.239',
        'PORT': '20003',
    },
    'region2': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'region2',
        'USER': 'region2',
        'PASSWORD': 'region2',
        'HOST': '5.179.102.239',
        'PORT': '20004',
    },
    'people': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'people',
        'USER': 'admin',
        'PASSWORD': 'admin',
        'HOST': '5.179.102.239',
        'PORT': '20004',
    },
       'gov_verify': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'gov_verify',
        'USER': 'voterauth',
        'PASSWORD': 'voterauth',
        'HOST': '5.179.102.239',
        'PORT': '20002',
    }
}


#To go back to local DB
'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'admin',
        'USER': 'admin',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'voterauth': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'voterauth',
        'USER': 'voterauth',
        'PASSWORD': 'voterauth',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'region1': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'region1',
        'USER': 'region1',
        'PASSWORD': 'region1',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'region2': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'region2',
        'USER': 'region2',
        'PASSWORD': 'region2',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'people': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'people',
        'USER': 'admin',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}'''

DATABASE_ROUTERS = ['voting_system.routers.dbRouter']

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'



SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.SHA1PasswordHasher',
    'django.contrib.auth.hashers.MD5PasswordHasher',
    'django.contrib.auth.hashers.UnsaltedSHA1PasswordHasher',
    'django.contrib.auth.hashers.UnsaltedMD5PasswordHasher',
    'django.contrib.auth.hashers.CryptPasswordHasher',
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/var/www/static/',
]