# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-15 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_system', '0003_finalcheck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='finalCheck',
        ),
    ]
