from .login import *
from .candidate import *
from .role import *
from .party import *
from .election import *
from .check_code import *
from .check_password import *
from .role import *
from .admin import *
from .region import *