from .admin import *
from .admin_role import *
from .candidate import *
from .election import *
from .election_candidate import *
from .election_party import *
from .election_region import *
from .party import *
from .region import *
from .region1_votes import *
from .region2_votes import *
from .role import *
from .test import *
from .voter_auth import *
from .voter_code import *